# Generated by Django 3.2.17 on 2023-03-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cgpa',
            field=models.FloatField(default=9.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default='Bhubaneswar'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.TextField(default='789456321'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.TextField(default='user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.TextField(default='male'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institute',
            field=models.TextField(default='Silicon Institute of Technology'),
        ),
        migrations.AddField(
            model_name='profile',
            name='programme',
            field=models.TextField(default='B.Tech'),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.TextField(default='Odisha'),
        ),
        migrations.AddField(
            model_name='profile',
            name='yop',
            field=models.TextField(default='2023'),
        ),
    ]
