# Generated by Django 3.2 on 2023-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230301_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Bhubaneswar', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='789456321', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='user', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='male', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(default='Silicon Institute of Technology', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='programme',
            field=models.CharField(default='B.Tech', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Odisha', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(default='2023', max_length=4),
        ),
    ]
