# Generated by Django 3.2.17 on 2023-04-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230302_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='programme',
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.TECH', 'Bachelor of Technology'), ('MSc', 'Master of Science, Data Science'), ('OTH', 'others'), ('M.TECH', 'Master of Technology'), ('MCA', 'Master of Computer Applications')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('others', 'Others'), ('male', 'Male'), ('female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('OTH', 'others'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2024', '2024'), ('2026', '2026'), ('2023', '2023'), ('2025', '2025')], default='2023', max_length=4),
        ),
    ]
