# Generated by Django 3.2.17 on 2023-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230411_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('OTH', 'others'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar')], max_length=50),
        ),
    ]
