# Generated by Django 3.2.17 on 2023-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.TECH', 'Bachelor of Technology'), ('OTH', 'others'), ('MCA', 'Master of Computer Applications'), ('M.TECH', 'Master of Technology'), ('MSc', 'Master of Science, Data Science')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('others', 'Others'), ('female', 'Female'), ('male', 'Male')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('OTH', 'others'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2025', '2025'), ('2023', '2023'), ('2024', '2024'), ('2026', '2026')], default='2023', max_length=4),
        ),
    ]
