# Generated by Django 3.2.17 on 2023-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230414_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('OTH', 'others'), ('M.TECH', 'Master of Technology'), ('B.TECH', 'Bachelor of Technology'), ('MSc', 'Master of Science, Data Science'), ('MCA', 'Master of Computer Applications')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('OTH', 'others'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('GIET GNPR', 'GIET University, Gunupur'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023')], default='2023', max_length=4),
        ),
    ]
