# Generated by Django 3.2.17 on 2023-04-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230419_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('M.TECH', 'Master of Technology'), ('OTH', 'others'), ('B.TECH', 'Bachelor of Technology'), ('MCA', 'Master of Computer Applications'), ('MSc', 'Master of Science, Data Science')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('others', 'Others'), ('female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('OTH', 'others'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('GIET GNPR', 'GIET University, Gunupur'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2026', '2026'), ('2025', '2025')], default='2023', max_length=4),
        ),
    ]
