# Generated by Django 3.2.17 on 2023-04-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230419_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('MCA', 'Master of Computer Applications'), ('MSc', 'Master of Science, Data Science'), ('B.TECH', 'Bachelor of Technology'), ('OTH', 'others'), ('M.TECH', 'Master of Technology')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('others', 'Others'), ('male', 'Male')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('OTH', 'others'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2023', '2023'), ('2026', '2026')], default='2023', max_length=4),
        ),
    ]
