# Generated by Django 3.2.17 on 2023-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230419_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('MCA', 'Master of Computer Applications'), ('MSc', 'Master of Science, Data Science'), ('M.TECH', 'Master of Technology'), ('OTH', 'others'), ('B.TECH', 'Bachelor of Technology')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('others', 'Others'), ('female', 'Female')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('OTH', 'others'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('GIET GNPR', 'GIET University, Gunupur'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2026', '2026'), ('2025', '2025'), ('2024', '2024'), ('2023', '2023')], default='2023', max_length=4),
        ),
    ]
