# Generated by Django 3.2.17 on 2023-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230420_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.TECH', 'Bachelor of Technology'), ('M.TECH', 'Master of Technology'), ('MSc', 'Master of Science, Data Science'), ('OTH', 'others'), ('MCA', 'Master of Computer Applications')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('GIET GNPR', 'GIET University, Gunupur'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('OTH', 'others'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2026', '2026'), ('2025', '2025'), ('2023', '2023'), ('2024', '2024')], default='2023', max_length=4),
        ),
    ]
