# Generated by Django 3.2.17 on 2023-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230420_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('M.TECH', 'Master of Technology'), ('MSc', 'Master of Science, Data Science'), ('B.TECH', 'Bachelor of Technology'), ('MCA', 'Master of Computer Applications'), ('OTH', 'others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('SSU CTC', 'Sri Sri University, Cuttack'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('OTH', 'others'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2026', '2026'), ('2025', '2025'), ('2023', '2023'), ('2024', '2024')], default='2023', max_length=4),
        ),
    ]
