# Generated by Django 3.2.17 on 2023-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230423_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('MSc', 'Master of Science, Data Science'), ('B.TECH', 'Bachelor of Technology'), ('M.TECH', 'Master of Technology'), ('MCA', 'Master of Computer Applications'), ('OTH', 'others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('OTH', 'others'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2025', '2025'), ('2026', '2026')], default='2023', max_length=4),
        ),
    ]
