# Generated by Django 3.2.17 on 2023-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230423_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('M.TECH', 'Master of Technology'), ('MCA', 'Master of Computer Applications'), ('OTH', 'others'), ('B.TECH', 'Bachelor of Technology'), ('MSc', 'Master of Science, Data Science')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('OTH', 'others'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('GIET GNPR', 'GIET University, Gunupur'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2025', '2025'), ('2023', '2023'), ('2024', '2024'), ('2026', '2026')], default='2023', max_length=4),
        ),
    ]
