# Generated by Django 3.2.17 on 2023-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230426_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('M.TECH', 'Master of Technology'), ('MCA', 'Master of Computer Applications'), ('B.TECH', 'Bachelor of Technology'), ('MSc', 'Master of Science, Data Science'), ('OTH', 'others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('others', 'Others')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('GIET GNPR', 'GIET University, Gunupur'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('OTH', 'others'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2025', '2025'), ('2023', '2023'), ('2026', '2026'), ('2024', '2024')], default='2023', max_length=4),
        ),
    ]
