# Generated by Django 3.2.17 on 2023-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20230426_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('MCA', 'Master of Computer Applications'), ('OTH', 'others'), ('MSc', 'Master of Science, Data Science'), ('M.TECH', 'Master of Technology'), ('B.TECH', 'Bachelor of Technology')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('others', 'Others'), ('female', 'Female'), ('male', 'Male')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('OTH', 'others'), ('GIET GNPR', 'GIET University, Gunupur'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2026', '2026'), ('2024', '2024'), ('2025', '2025'), ('2023', '2023')], default='2023', max_length=4),
        ),
    ]
