# Generated by Django 3.2.17 on 2023-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230427_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(default='Hello there, I am using Integrated Coding', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('M.TECH', 'Master of Technology'), ('MSc', 'Master of Science, Data Science'), ('OTH', 'others'), ('B.TECH', 'Bachelor of Technology'), ('MCA', 'Master of Computer Applications')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('OTH', 'others'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('GIET GNPR', 'GIET University, Gunupur'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2026', '2026'), ('2025', '2025'), ('2023', '2023'), ('2024', '2024')], default='2023', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(to='users.Skill'),
        ),
    ]
