# Generated by Django 3.2.17 on 2023-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230427_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Hello there, I am using Integrated Coding'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('B.TECH', 'Bachelor of Technology'), ('MCA', 'Master of Computer Applications'), ('MSc', 'Master of Science, Data Science'), ('M.TECH', 'Master of Technology'), ('OTH', 'others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('others', 'Others'), ('male', 'Male')], max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('CET', 'College of Engineering and Technology, Bhubaneswar'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('OTH', 'others'), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2024', '2024'), ('2023', '2023')], default='2023', max_length=4),
        ),
    ]
