# Generated by Django 4.2 on 2023-04-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230427_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('MCA', 'Master of Computer Applications'), ('M.TECH', 'Master of Technology'), ('MSc', 'Master of Science, Data Science'), ('B.TECH', 'Bachelor of Technology'), ('OTH', 'others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institute',
            field=models.CharField(blank=True, choices=[('CVRGU BBSR', 'C. V. Raman Global University, Bhubaneswar'), ('KIIT BBSR', 'Kalinga Institute of Industrial Technology, Bhubaneswar'), ('IIIT BBSR', 'International Institute of Information Technology, Bhubaneswar'), ('ITER BBSR', 'Institute of Technical Education and Research, Bhubaneswar'), ('SIT SBP', 'Silicon Institute of Technology, Sambalpur'), ('CUTM BBSR', 'Centurion University of Technology and Management, Bhubaneswar'), ('XIM BBSR', 'XIM University, Bhubaneswar'), ('IIT BBSR', 'Indian Institute of Technology, Bhrbaneswar'), ('GIET GNPR', 'GIET University, Gunupur'), ('BPUT BBSR', 'Biju Patnaik University of Technology, Rourkela'), ('OTH', 'others'), ('BEC BBSR', 'Bhubaneswar Engineering College, Bhubaneswar'), ('GIFT', 'Gandhi Institute for Technology, Bhubaneswar'), ('VSSUT SBP', 'Veer Surendra Sai University of Technology, Burla'), ('NIST BAM', 'National Institute of Science and Technology, Berhampur'), ('SIT BBSR', 'Silicon Institute of Technology, Bhubaneswar'), ('SOA BBSR', "Siksha 'O' Anusandhan University, Bhubaneswar"), ('IGIT DNKL', 'Indira Gandhi Institute of Technology, Dhenkanal'), ('COEB BBSR', 'College of Engineering Bhubaneswar, Bhubaneswar'), ('SSU CTC', 'Sri Sri University, Cuttack'), ('NIT RRK', 'National Institute of Technology, Rourkela'), ('CUTM PLH', 'Centurion University of Technology and Management, Paralkhemundi'), ('CET', 'College of Engineering and Technology, Bhubaneswar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yop',
            field=models.CharField(choices=[('2025', '2025'), ('2024', '2024'), ('2026', '2026'), ('2023', '2023')], default='2023', max_length=4),
        ),
    ]
