# Generated by Django 3.2.17 on 2023-04-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackerRankID', models.CharField(max_length=100)),
                ('codechefID', models.CharField(max_length=100)),
                ('leetcodeID', models.CharField(max_length=100)),
                ('codeforcesID', models.CharField(max_length=100)),
                ('spojID', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
