# Generated by Django 3.2.17 on 2023-04-08 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding_profile', '0002_auto_20230404_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformid',
            name='codechefID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platformid',
            name='codeforcesID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platformid',
            name='hackerRankID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platformid',
            name='leetcodeID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='platformid',
            name='spojID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SpojDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveBigIntegerField(default=0)),
                ('no_of_contest_attempted', models.PositiveIntegerField(default=0)),
                ('contest_rating', models.PositiveIntegerField(default=0)),
                ('no_of_problem_solved', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeetcodeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveBigIntegerField(default=0)),
                ('no_of_contest_attempted', models.PositiveIntegerField(default=0)),
                ('contest_rating', models.PositiveIntegerField(default=0)),
                ('no_of_problem_solved', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HackerRankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Badges', models.CharField(blank=True, max_length=100000)),
                ('skill_verified', models.CharField(blank=True, max_length=100000)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesDetals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveBigIntegerField(default=0)),
                ('no_of_contest_attempted', models.PositiveIntegerField(default=0)),
                ('contest_rating', models.PositiveIntegerField(default=0)),
                ('no_of_problem_solved', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodechefDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveBigIntegerField(default=0)),
                ('no_of_contest_attempted', models.PositiveIntegerField(default=0)),
                ('contest_rating', models.PositiveIntegerField(default=0)),
                ('no_of_problem_solved', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveBigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
