# Generated by Django 3.2.17 on 2023-04-09 07:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coding_profile', '0003_auto_20230408_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeforcesDetals',
            new_name='CodeforcesDetails',
        ),
    ]
