# Generated by Django 3.2.17 on 2023-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_profile', '0005_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
