# Generated by Django 3.2.17 on 2023-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_profile', '0007_remove_leaderboard_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeforcesdetails',
            name='rank',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
