# Generated by Django 3.2.17 on 2023-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_profile', '0008_alter_codeforcesdetails_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='total_contest_attempted',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_problem_solved',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
