# Generated by Django 3.2.17 on 2023-03-01 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='upcoming', max_length=10)),
                ('platform', models.ForeignKey(default='platform', on_delete=django.db.models.deletion.PROTECT, to='contest.platform')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
