# Generated by Django 3.2.17 on 2023-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_alter_contest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('constant', 'Constant'), ('expired', 'Expired'), ('ongoing', 'Ongoing')], default='upcoming', max_length=10),
        ),
    ]
