# Generated by Django 4.2 on 2023-04-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_alter_contest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('constant', 'Constant'), ('expired', 'Expired'), ('ongoing', 'Ongoing')], default='upcoming', max_length=10),
        ),
    ]
