# Generated by Django 3.2.17 on 2023-04-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestQuestion',
            fields=[
                ('question_no', models.AutoField(primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=1000)),
                ('question_link', models.CharField(max_length=10000)),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
