# Generated by Django 3.2.17 on 2023-04-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
