# Generated by Django 3.2.17 on 2023-04-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20230410_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestquestion',
            name='question_type',
            field=models.CharField(choices=[('searching & sorting', 'Searching & Sorting'), ('binary search tree', 'Binary Search Tree'), ('bit maniputation', 'Bit Maniputaion'), ('graph', 'Graph'), ('string', 'String'), ('dynamic programming', 'Dynamic Programming'), ('backtracking', 'Backtracking'), ('stack & queue', 'Stack & Queue'), ('greedy', 'Greedy'), ('array', 'Array '), ('linkedlist', 'Linkedlist'), ('heap', 'Heap'), ('matrix', 'Matrix'), ('binary tree', 'Binary Tree')], default='array', max_length=30),
        ),
    ]
