# Generated by Django 3.2.17 on 2023-04-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230411_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestquestion',
            name='question_type',
            field=models.CharField(choices=[('heap', 'Heap'), ('greedy', 'Greedy'), ('binary search tree', 'Binary Search Tree'), ('array', 'Array '), ('stack & queue', 'Stack & Queue'), ('string', 'String'), ('graph', 'Graph'), ('searching & sorting', 'Searching & Sorting'), ('dynamic programming', 'Dynamic Programming'), ('bit maniputation', 'Bit Maniputaion'), ('backtracking', 'Backtracking'), ('binary tree', 'Binary Tree'), ('linkedlist', 'Linkedlist'), ('matrix', 'Matrix')], default='array', max_length=30),
        ),
    ]
