# Generated by Django 3.2.17 on 2023-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20230411_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('hard', 'Hard'), ('easy', 'Easy')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestquestion',
            name='question_type',
            field=models.CharField(choices=[('matrix', 'Matrix'), ('array', 'Array '), ('graph', 'Graph'), ('dynamic programming', 'Dynamic Programming'), ('string', 'String'), ('binary search tree', 'Binary Search Tree'), ('searching & sorting', 'Searching & Sorting'), ('heap', 'Heap'), ('backtracking', 'Backtracking'), ('stack & queue', 'Stack & Queue'), ('greedy', 'Greedy'), ('binary tree', 'Binary Tree'), ('bit maniputation', 'Bit Maniputaion'), ('linkedlist', 'Linkedlist')], default='array', max_length=30),
        ),
    ]
