# Generated by Django 3.2.17 on 2023-04-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20230414_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestquestion',
            name='question_type',
            field=models.CharField(choices=[('backtracking', 'Backtracking'), ('array', 'Array '), ('binary tree', 'Binary Tree'), ('bit maniputation', 'Bit Maniputaion'), ('heap', 'Heap'), ('matrix', 'Matrix'), ('string', 'String'), ('linkedlist', 'Linkedlist'), ('greedy', 'Greedy'), ('dynamic programming', 'Dynamic Programming'), ('binary search tree', 'Binary Search Tree'), ('stack & queue', 'Stack & Queue'), ('searching & sorting', 'Searching & Sorting'), ('graph', 'Graph')], default='array', max_length=30),
        ),
    ]
