# Generated by Django 3.2.17 on 2023-04-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20230419_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestquestion',
            name='question_type',
            field=models.CharField(choices=[('dynamic programming', 'Dynamic Programming'), ('heap', 'Heap'), ('string', 'String'), ('binary tree', 'Binary Tree'), ('bit maniputation', 'Bit Maniputaion'), ('stack & queue', 'Stack & Queue'), ('greedy', 'Greedy'), ('searching & sorting', 'Searching & Sorting'), ('linkedlist', 'Linkedlist'), ('graph', 'Graph'), ('backtracking', 'Backtracking'), ('array', 'Array '), ('matrix', 'Matrix'), ('binary search tree', 'Binary Search Tree')], default='array', max_length=30),
        ),
    ]
