# Generated by Django 3.2.17 on 2023-04-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_contestquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('hard', 'Hard'), ('easy', 'Easy'), ('medium', 'Medium')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='contestquestion',
            name='question_type',
            field=models.CharField(choices=[('searching & sorting', 'Searching & Sorting'), ('binary tree', 'Binary Tree'), ('graph', 'Graph'), ('backtracking', 'Backtracking'), ('greedy', 'Greedy'), ('heap', 'Heap'), ('binary search tree', 'Binary Search Tree'), ('dynamic programming', 'Dynamic Programming'), ('array', 'Array '), ('matrix', 'Matrix'), ('stack & queue', 'Stack & Queue'), ('linkedlist', 'Linkedlist'), ('string', 'String'), ('bit maniputation', 'Bit Maniputaion')], default='array', max_length=30),
        ),
    ]
