# Generated by Django 3.2.17 on 2023-04-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20230420_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard'), ('medium', 'Medium')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('matrix', 'Matrix'), ('heap', 'Heap'), ('binary tree', 'Binary Tree'), ('greedy', 'Greedy'), ('array', 'Array '), ('searching & sorting', 'Searching & Sorting'), ('dynamic programming', 'Dynamic Programming'), ('backtracking', 'Backtracking'), ('graph', 'Graph'), ('linkedlist', 'Linkedlist'), ('stack & queue', 'Stack & Queue'), ('trie', 'Trie'), ('binary search tree', 'Binary Search Tree'), ('string', 'String'), ('bit maniputation', 'Bit Maniputaion')], default='array', max_length=30),
        ),
    ]
