# Generated by Django 3.2.17 on 2023-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20230420_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('medium', 'Medium'), ('easy', 'Easy'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('matrix', 'Matrix'), ('trie', 'Trie'), ('heap', 'Heap'), ('bit maniputation', 'Bit Maniputaion'), ('linkedlist', 'Linkedlist'), ('greedy', 'Greedy'), ('string', 'String'), ('backtracking', 'Backtracking'), ('binary search tree', 'Binary Search Tree'), ('stack & queue', 'Stack & Queue'), ('dynamic programming', 'Dynamic Programming'), ('graph', 'Graph'), ('binary tree', 'Binary Tree'), ('searching & sorting', 'Searching & Sorting'), ('array', 'Array ')], default='array', max_length=30),
        ),
        migrations.AlterField(
            model_name='usercodingquestion',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
