# Generated by Django 3.2.17 on 2023-04-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20230420_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('hard', 'Hard'), ('medium', 'Medium')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('stack & queue', 'Stack & Queue'), ('graph', 'Graph'), ('dynamic programming', 'Dynamic Programming'), ('searching & sorting', 'Searching & Sorting'), ('binary tree', 'Binary Tree'), ('trie', 'Trie'), ('array', 'Array '), ('matrix', 'Matrix'), ('binary search tree', 'Binary Search Tree'), ('linkedlist', 'Linkedlist'), ('bit maniputation', 'Bit Maniputaion'), ('greedy', 'Greedy'), ('string', 'String'), ('backtracking', 'Backtracking'), ('heap', 'Heap')], default='array', max_length=30),
        ),
    ]
