# Generated by Django 3.2.17 on 2023-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20230423_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('backtracking', 'Backtracking'), ('heap', 'Heap'), ('dynamic programming', 'Dynamic Programming'), ('matrix', 'Matrix'), ('binary tree', 'Binary Tree'), ('searching & sorting', 'Searching & Sorting'), ('trie', 'Trie'), ('string', 'String'), ('bit maniputation', 'Bit Maniputaion'), ('greedy', 'Greedy'), ('binary search tree', 'Binary Search Tree'), ('stack & queue', 'Stack & Queue'), ('graph', 'Graph'), ('array', 'Array '), ('linkedlist', 'Linkedlist')], default='array', max_length=30),
        ),
    ]
