# Generated by Django 3.2.17 on 2023-04-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20230423_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('searching & sorting', 'Searching & Sorting'), ('array', 'Array '), ('heap', 'Heap'), ('backtracking', 'Backtracking'), ('binary tree', 'Binary Tree'), ('bit maniputation', 'Bit Maniputaion'), ('binary search tree', 'Binary Search Tree'), ('dynamic programming', 'Dynamic Programming'), ('matrix', 'Matrix'), ('string', 'String'), ('stack & queue', 'Stack & Queue'), ('greedy', 'Greedy'), ('graph', 'Graph'), ('trie', 'Trie'), ('linkedlist', 'Linkedlist')], default='array', max_length=30),
        ),
    ]
