# Generated by Django 3.2.17 on 2023-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20230426_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('Greedy', 'Greedy'), ('Backtracking', 'Backtracking'), ('String', 'String'), ('Array', 'Array '), ('Matrix', 'Matrix'), ('Graph', 'Graph'), ('Binary search tree', 'Binary Search Tree'), ('Heap', 'Heap'), ('Linkedlist', 'Linkedlist'), ('Dynamic programming', 'Dynamic Programming'), ('Stack & Queue', 'Stack & Queue'), ('Trie', 'Trie'), ('Binary tree', 'Binary Tree'), ('Bit Maniputation', 'Bit Maniputaion'), ('Searching & Sorting', 'Searching & Sorting')], default='Array', max_length=30),
        ),
    ]
