# Generated by Django 3.2.17 on 2023-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_codingquestion_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('Array', 'Array '), ('Searching & Sorting', 'Searching & Sorting'), ('Greedy', 'Greedy'), ('Linkedlist', 'Linkedlist'), ('Trie', 'Trie'), ('Bit Maniputation', 'Bit Maniputaion'), ('Matrix', 'Matrix'), ('String', 'String'), ('Binary tree', 'Binary Tree'), ('Graph', 'Graph'), ('Dynamic programming', 'Dynamic Programming'), ('Backtracking', 'Backtracking'), ('Stack & Queue', 'Stack & Queue'), ('Binary search tree', 'Binary Search Tree'), ('Heap', 'Heap')], default='Array', max_length=30),
        ),
    ]
