# Generated by Django 3.2.17 on 2023-04-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20230427_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('Matrix', 'Matrix'), ('String', 'String'), ('Binary search tree', 'Binary Search Tree'), ('Dynamic programming', 'Dynamic Programming'), ('Linkedlist', 'Linkedlist'), ('Heap', 'Heap'), ('Trie', 'Trie'), ('Binary tree', 'Binary Tree'), ('Greedy', 'Greedy'), ('Array', 'Array '), ('Graph', 'Graph'), ('Searching & Sorting', 'Searching & Sorting'), ('Stack & Queue', 'Stack & Queue'), ('Backtracking', 'Backtracking'), ('Bit Maniputation', 'Bit Maniputaion')], default='Array', max_length=30),
        ),
    ]
