# Generated by Django 4.2 on 2023-04-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20230427_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='question_difficulty',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Hard', 'Hard'), ('Easy', 'Easy')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='question_type',
            field=models.CharField(choices=[('Heap', 'Heap'), ('Stack & Queue', 'Stack & Queue'), ('String', 'String'), ('Array', 'Array '), ('Dynamic programming', 'Dynamic Programming'), ('Linkedlist', 'Linkedlist'), ('Trie', 'Trie'), ('Binary tree', 'Binary Tree'), ('Searching & Sorting', 'Searching & Sorting'), ('Graph', 'Graph'), ('Binary search tree', 'Binary Search Tree'), ('Bit Maniputation', 'Bit Maniputaion'), ('Matrix', 'Matrix'), ('Greedy', 'Greedy'), ('Backtracking', 'Backtracking')], default='Array', max_length=30),
        ),
    ]
